# -*- encoding: utf-8 -*-

=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "kubevirt/version"

Gem::Specification.new do |s|
  s.name        = "kubevirt"
  s.version     = Kubevirt::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["ManageIQ Developers"]
  s.email       = ["kubevirt-dev@googlegroups.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Kubevirt SDK"
  s.description = "Ruby gem for Kubevirt"
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
