=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubevirt::K8sIoApiCoreV1PodAffinityTerm
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kubevirt::K8sIoApiCoreV1PodAffinityTerm do
  let(:instance) { Kubevirt::K8sIoApiCoreV1PodAffinityTerm.new }

  describe 'test an instance of K8sIoApiCoreV1PodAffinityTerm' do
    it 'should create an instance of K8sIoApiCoreV1PodAffinityTerm' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kubevirt::K8sIoApiCoreV1PodAffinityTerm)
    end
  end

  describe 'test attribute "label_selector"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "match_label_keys"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mismatch_label_keys"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "namespace_selector"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "namespaces"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "topology_key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
