=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubevirt::V1alpha1VirtualMachinePoolSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kubevirt::V1alpha1VirtualMachinePoolSpec do
  let(:instance) { Kubevirt::V1alpha1VirtualMachinePoolSpec.new }

  describe 'test an instance of V1alpha1VirtualMachinePoolSpec' do
    it 'should create an instance of V1alpha1VirtualMachinePoolSpec' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kubevirt::V1alpha1VirtualMachinePoolSpec)
    end
  end

  describe 'test attribute "paused"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "replicas"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "selector"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "virtual_machine_template"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
