=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module Kubevirt
  # Hyperv specific features.
  class V1FeatureHyperv
    attr_accessor :evmcs

    attr_accessor :frequencies

    attr_accessor :ipi

    attr_accessor :reenlightenment

    attr_accessor :relaxed

    attr_accessor :reset

    attr_accessor :runtime

    attr_accessor :spinlocks

    attr_accessor :synic

    attr_accessor :synictimer

    attr_accessor :tlbflush

    attr_accessor :vapic

    attr_accessor :vendorid

    attr_accessor :vpindex

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'evmcs' => :'evmcs',
        :'frequencies' => :'frequencies',
        :'ipi' => :'ipi',
        :'reenlightenment' => :'reenlightenment',
        :'relaxed' => :'relaxed',
        :'reset' => :'reset',
        :'runtime' => :'runtime',
        :'spinlocks' => :'spinlocks',
        :'synic' => :'synic',
        :'synictimer' => :'synictimer',
        :'tlbflush' => :'tlbflush',
        :'vapic' => :'vapic',
        :'vendorid' => :'vendorid',
        :'vpindex' => :'vpindex'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'evmcs' => :'V1FeatureState',
        :'frequencies' => :'V1FeatureState',
        :'ipi' => :'V1FeatureState',
        :'reenlightenment' => :'V1FeatureState',
        :'relaxed' => :'V1FeatureState',
        :'reset' => :'V1FeatureState',
        :'runtime' => :'V1FeatureState',
        :'spinlocks' => :'V1FeatureSpinlocks',
        :'synic' => :'V1FeatureState',
        :'synictimer' => :'V1SyNICTimer',
        :'tlbflush' => :'V1FeatureState',
        :'vapic' => :'V1FeatureState',
        :'vendorid' => :'V1FeatureVendorID',
        :'vpindex' => :'V1FeatureState'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1FeatureHyperv` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1FeatureHyperv`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'evmcs')
        self.evmcs = attributes[:'evmcs']
      end

      if attributes.key?(:'frequencies')
        self.frequencies = attributes[:'frequencies']
      end

      if attributes.key?(:'ipi')
        self.ipi = attributes[:'ipi']
      end

      if attributes.key?(:'reenlightenment')
        self.reenlightenment = attributes[:'reenlightenment']
      end

      if attributes.key?(:'relaxed')
        self.relaxed = attributes[:'relaxed']
      end

      if attributes.key?(:'reset')
        self.reset = attributes[:'reset']
      end

      if attributes.key?(:'runtime')
        self.runtime = attributes[:'runtime']
      end

      if attributes.key?(:'spinlocks')
        self.spinlocks = attributes[:'spinlocks']
      end

      if attributes.key?(:'synic')
        self.synic = attributes[:'synic']
      end

      if attributes.key?(:'synictimer')
        self.synictimer = attributes[:'synictimer']
      end

      if attributes.key?(:'tlbflush')
        self.tlbflush = attributes[:'tlbflush']
      end

      if attributes.key?(:'vapic')
        self.vapic = attributes[:'vapic']
      end

      if attributes.key?(:'vendorid')
        self.vendorid = attributes[:'vendorid']
      end

      if attributes.key?(:'vpindex')
        self.vpindex = attributes[:'vpindex']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          evmcs == o.evmcs &&
          frequencies == o.frequencies &&
          ipi == o.ipi &&
          reenlightenment == o.reenlightenment &&
          relaxed == o.relaxed &&
          reset == o.reset &&
          runtime == o.runtime &&
          spinlocks == o.spinlocks &&
          synic == o.synic &&
          synictimer == o.synictimer &&
          tlbflush == o.tlbflush &&
          vapic == o.vapic &&
          vendorid == o.vendorid &&
          vpindex == o.vpindex
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [evmcs, frequencies, ipi, reenlightenment, relaxed, reset, runtime, spinlocks, synic, synictimer, tlbflush, vapic, vendorid, vpindex].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Kubevirt.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
