=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Kubevirt
  # BackupOptions are options used to configure virtual machine backup job
  class V1alpha1BackupOptions
    attr_accessor :backup_cert

    attr_accessor :backup_key

    attr_accessor :backup_name

    # Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    attr_accessor :backup_start_time

    attr_accessor :ca_cert

    attr_accessor :cmd

    attr_accessor :export_server_addr

    attr_accessor :export_server_name

    attr_accessor :incremental

    attr_accessor :mode

    attr_accessor :skip_quiesce

    attr_accessor :target_path

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'backup_cert' => :'backupCert',
        :'backup_key' => :'backupKey',
        :'backup_name' => :'backupName',
        :'backup_start_time' => :'backupStartTime',
        :'ca_cert' => :'caCert',
        :'cmd' => :'cmd',
        :'export_server_addr' => :'exportServerAddr',
        :'export_server_name' => :'exportServerName',
        :'incremental' => :'incremental',
        :'mode' => :'mode',
        :'skip_quiesce' => :'skipQuiesce',
        :'target_path' => :'targetPath'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'backup_cert' => :'String',
        :'backup_key' => :'String',
        :'backup_name' => :'String',
        :'backup_start_time' => :'Time',
        :'ca_cert' => :'String',
        :'cmd' => :'String',
        :'export_server_addr' => :'String',
        :'export_server_name' => :'String',
        :'incremental' => :'String',
        :'mode' => :'String',
        :'skip_quiesce' => :'Boolean',
        :'target_path' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1alpha1BackupOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1alpha1BackupOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'backup_cert')
        self.backup_cert = attributes[:'backup_cert']
      end

      if attributes.key?(:'backup_key')
        self.backup_key = attributes[:'backup_key']
      end

      if attributes.key?(:'backup_name')
        self.backup_name = attributes[:'backup_name']
      end

      if attributes.key?(:'backup_start_time')
        self.backup_start_time = attributes[:'backup_start_time']
      end

      if attributes.key?(:'ca_cert')
        self.ca_cert = attributes[:'ca_cert']
      end

      if attributes.key?(:'cmd')
        self.cmd = attributes[:'cmd']
      end

      if attributes.key?(:'export_server_addr')
        self.export_server_addr = attributes[:'export_server_addr']
      end

      if attributes.key?(:'export_server_name')
        self.export_server_name = attributes[:'export_server_name']
      end

      if attributes.key?(:'incremental')
        self.incremental = attributes[:'incremental']
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      end

      if attributes.key?(:'skip_quiesce')
        self.skip_quiesce = attributes[:'skip_quiesce']
      end

      if attributes.key?(:'target_path')
        self.target_path = attributes[:'target_path']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          backup_cert == o.backup_cert &&
          backup_key == o.backup_key &&
          backup_name == o.backup_name &&
          backup_start_time == o.backup_start_time &&
          ca_cert == o.ca_cert &&
          cmd == o.cmd &&
          export_server_addr == o.export_server_addr &&
          export_server_name == o.export_server_name &&
          incremental == o.incremental &&
          mode == o.mode &&
          skip_quiesce == o.skip_quiesce &&
          target_path == o.target_path
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [backup_cert, backup_key, backup_name, backup_start_time, ca_cert, cmd, export_server_addr, export_server_name, incremental, mode, skip_quiesce, target_path].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Kubevirt.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
