name: Update gem from OpenAPI Spec

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  openapi-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up openapi-generator-cli
      run: wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.9.0/openapi-generator-cli-7.9.0.jar -O openapi-generator-cli.jar
    - name: Validate OpenAPI Spec
      run: java -jar openapi-generator-cli.jar generate --input-spec https://raw.githubusercontent.com/kubevirt/kubevirt/refs/heads/main/api/openapi-spec/swagger.json --skip-validate-spec --generator-name ruby --config .openapi-config.json
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        add-paths: |
          docs
          lib
          spec
        commit-message: Update kubevirt gem
        branch: update_kubevirt
        author: ManageIQ Bot <bot@manageiq.org>
        committer: ManageIQ Bot <bot@manageiq.org>
        delete-branch: true
        labels: enhancement
        title: Update Kubevirt Gem
